### ISSUE TITLE
Resolve Clippy errors

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari_utilities#42]
Clippy errors are now a hard error in CI, but there are a few legacy issues (or version creep issues) that currently would lead every PR to fail.

This is a good first issue to sort out.

**Comment by aldine-guyon** [comment]
Hi @CjS77 I'd like to pick this issue if no one took it yet.
Basically there are 2 ways to resolve it. 
1. put some clippy flags in `.cargo/config.toml`.
2. put clippy flags in CI files: `clippy-check.yml` & `test.yml`

**Comment by delta1** [comment]
@aldine-guyon i think the goal is to run cargo clippy yourself and fix the code generating the warnings/errors

**Comment by CjS77** [comment]
Exactly. Don't mask the errors, fix 'em :)

**Comment by aldine-guyon** [comment]
I've just checked again, all errors seems resolved now. 
Some [pipelines](https://github.com/tari-project/tari_utilities/runs/6877510774?check_suite_focus=true) were failed but its old, maybe I saw it too late.

@CjS77 maybe you got me wrong, I mean there are some clippy warnings seems harmless. 
I usually allowed some flags to check real errors which clippy complaint about.
For e.g., ` -A clippy::identity_op -A clippy::collapsible_else_if -A clippy::unnecessary_fold`

**Comment by CjS77** [comment]
I should have been more explicit. The idea is to add the hard requirement that `cargo lints clippy --all-features --all-targets` passes. It does look like most of the issues have been fixed (🚀 ), but I still see:

```
cargo lints clippy --all-features --all-targets
   Compiling libc v0.2.112
  ..
    Checking tari_utilities v0.4.4 (/Users/cayle/tari/tari_utilities)
error: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/serde/hex.rs:123:57
    |
123 |         let restored: HexOrBytes = serde_json::from_str(&expected).unwrap();
    |                                                         ^^^^^^^^^ help: change this to: `expected`
    |
    = note: `-D clippy::needless-borrow` implied by `-D clippy::style`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```

**Comment by CjS77** [comment]
@aldine-guyon -- cool. Yes, warnings are fine. It won't be required to pass CI, but it would be great if they are eventually resolved one way or the other.
